sudo: true
language: php
php:
  - '7.1'

before_install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.31/hugo_0.31_Linux-64bit.tar.gz && tar xf hugo_0.31_Linux-64bit.tar.gz && sudo mv hugo /usr/local/bin

script:
  - composer install
  - php index-algolia.php
  - hugo
  - cd public && sshpass -p $SSH_PW scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r * shyimci@yoko.shyim.de:/var/www/shyim.me/web/
